### ISSUE TITLE
Fails to build on Linux Ubuntu 24.04. 

### ISSUE THREAD

**Issue by navinreddy23** [fdaines/go-architect#27]
Hi, 

I tried to use the tool by building on Linux. So far it has not been successful. Could you please help me in figuring out this issue?

```
> npm version                        
{
  npm: '10.9.0',
  node: '23.3.0'
}
```

```
~/Tools/go-architect on @245c79e2                                                                                                                                                                                                                                                        
> wails dev -tags webkit2_41
Wails CLI v2.9.2

Updated go.mod to use Go '1.20'
Updating go.mod to use Wails 'v2.9.2'
Executing: go mod tidy
.
.
.
.
.

Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:     
    > frontend@0.0.0 build
    > vue-tsc --noEmit && vite build
    
    src/utils/storage.ts(11,5): error TS2322: Type 'Project | undefined' is not assignable to type 'Project | null'.
      Type 'undefined' is not assignable to type 'Project | null'.
    
    

  ERROR   exit status 2
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

```

**Comment by navinreddy23** [comment]
navinreddy23:main

**Comment by navinreddy23** [comment]
https://github.com/go-architect/go-architect/pull/28
